Name: mail
Mode: dev

Pulsar:
  Url: "pulsar://localhost:6650"
  Main: "persistent://echo-wing/main"
  Dlq: "persistent://echo-wing/dlq/all"

Consul:
  Host: "localhost"
  Port: 8500
  Base: "echo_wing/"
  Token: ""
  Scheme: "http"

SMTP:
  Host: smtp.qq.com
  Port: 465
  FromName: "SimpleMail"
  Username: "haxxorbunny@qq.com"
  Password: "tygsxqljpqxaebga"
  TLS: true
  DefaultFrom: "haxxorbunny@qq.com"
